### ISSUE TITLE
异常导致应用崩溃

### ISSUE THREAD

**Issue by wchen9** [shadowsocksrr/shadowsocksr-android#145]
使用SSRR之后经常会挂一段时间出现应用直接崩溃，VPN状态也直接消失。

环境安卓8.1 OmniROM
异常堆栈：
--------- beginning of crash
05-31 14:00:10.530  6666  6666 E AndroidRuntime: FATAL EXCEPTION: main
05-31 14:00:10.530  6666  6666 E AndroidRuntime: Process: in.zhaoj.shadowsocksrr:bg, PID: 6666
05-31 14:00:10.530  6666  6666 E AndroidRuntime: android.app.RemoteServiceException: Bad notification posted from package in.zhaoj.shadowsocksrr: Couldn't inflate contentViewsandroid.widget.RemoteViews$ActionException: java.lang.NullPointerException: outValue
05-31 14:00:10.530  6666  6666 E AndroidRuntime:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1769)
05-31 14:00:10.530  6666  6666 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:106)
05-31 14:00:10.530  6666  6666 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:164)
05-31 14:00:10.530  6666  6666 E AndroidRuntime:  at android.app.ActivityThread.main(ActivityThread.java:6499)
05-31 14:00:10.530  6666  6666 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)
05-31 14:00:10.530  6666  6666 E AndroidRuntime:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-31 14:00:10.530  6666  6666 E AndroidRuntime:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-31 14:00:10.530  6666  6666 E AndroidRuntime:  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by Akkariiin** [comment]
先排除一下进程被杀掉的原因，另外是不是Xposed导致的也需要排除
