### ISSUE TITLE
ssrr在红米note4MTK开发版测速报错

### ISSUE THREAD

**Issue by chenhuaiyu** [shadowsocksrr/shadowsocksr-android#184]
java.lang.Exception: 状态码无效（#503）
	at com.github.shadowsocks.ProfileManagerActivity$$anon$4$$anonfun$run$1.apply(ProfileManagerActivity.scala:1071)
	at com.github.shadowsocks.ProfileManagerActivity$$anon$4$$anonfun$run$1.apply(ProfileManagerActivity.scala:1000)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.github.shadowsocks.ProfileManagerActivity$$anon$4.run(ProfileManagerActivity.scala:1000)
这个是错误代码，安卓版本6.0，MIUI版本是MIUI10.8.9.20 ssrr版本3.5.4

**Comment by chenhuaiyu** [comment]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
	... 1 more
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:515)
	at com.github.shadowsocks.aidl.IShadowsocksService$Stub$Proxy.getState(IShadowsocksService.java:119)
	at com.github.shadowsocks.Shadowsocks.updateState(Shadowsocks.scala:359)
	at com.github.shadowsocks.Shadowsocks.onServiceConnected(Shadowsocks.scala:182)
	at com.github.shadowsocks.ServiceBoundContext$ShadowsocksServiceConnection.onServiceConnected(ServiceBoundContext.scala:19)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1274)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1291)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5845)
	... 3 more
